/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("@/layouts/base/index.vue"),
  blank: () => import("@/layouts/blank/index.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  _builtin403: () => import("@/views/_builtin/403/index.vue"),
  _builtin404: () => import("@/views/_builtin/404/index.vue"),
  _builtin500: () => import("@/views/_builtin/500/index.vue"),
  _builtinIframePageUrl: () => import("@/views/_builtin/iframe-page/[url].vue"),
  _builtinLogin: () => import("@/views/_builtin/login/index.vue"),
  About: () => import("@/views/about/index.vue"),
  AgentConfig: () => import("@/views/agent/config/index.vue"),
  AlovaRequest: () => import("@/views/alova/request/index.vue"),
  AlovaScenes: () => import("@/views/alova/scenes/index.vue"),
  AlovaUser: () => import("@/views/alova/user/index.vue"),
  FunctionHideChildOne: () => import("@/views/function/hide-child/one/index.vue"),
  FunctionHideChildThree: () => import("@/views/function/hide-child/three/index.vue"),
  FunctionHideChildTwo: () => import("@/views/function/hide-child/two/index.vue"),
  FunctionMultiTab: () => import("@/views/function/multi-tab/index.vue"),
  FunctionRequest: () => import("@/views/function/request/index.vue"),
  FunctionSuperPage: () => import("@/views/function/super-page/index.vue"),
  FunctionTab: () => import("@/views/function/tab/index.vue"),
  FunctionToggleAuth: () => import("@/views/function/toggle-auth/index.vue"),
  Home: () => import("@/views/home/index.vue"),
  ManageAgent: () => import("@/views/manage/agent/index.vue"),
  ManageApi: () => import("@/views/manage/api/index.vue"),
  ManageLog: () => import("@/views/manage/log/index.vue"),
  ManageMenu: () => import("@/views/manage/menu/index.vue"),
  ManageRole: () => import("@/views/manage/role/index.vue"),
  ManageUser: () => import("@/views/manage/user/index.vue"),
  ManageUserDetailId: () => import("@/views/manage/user-detail/[id].vue"),
  Medic: () => import("@/views/medic/index.vue"),
  MedicalDiseaseList: () => import("@/views/medical/disease-list/index.vue"),
  MedicalExecutionDetailId: () => import("@/views/medical/execution-detail/[id].vue"),
  MultiMenuFirstChild: () => import("@/views/multi-menu/first_child/index.vue"),
  MultiMenuSecondChildHome: () => import("@/views/multi-menu/second_child_home/index.vue"),
  PluginBarcode: () => import("@/views/plugin/barcode/index.vue"),
  PluginChartsAntv: () => import("@/views/plugin/charts/antv/index.vue"),
  PluginChartsEcharts: () => import("@/views/plugin/charts/echarts/index.vue"),
  PluginChartsVchart: () => import("@/views/plugin/charts/vchart/index.vue"),
  PluginCopy: () => import("@/views/plugin/copy/index.vue"),
  PluginEditorMarkdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  PluginEditorQuill: () => import("@/views/plugin/editor/quill/index.vue"),
  PluginExcel: () => import("@/views/plugin/excel/index.vue"),
  PluginGanttDhtmlx: () => import("@/views/plugin/gantt/dhtmlx/index.vue"),
  PluginGanttVtable: () => import("@/views/plugin/gantt/vtable/index.vue"),
  PluginIcon: () => import("@/views/plugin/icon/index.vue"),
  PluginMap: () => import("@/views/plugin/map/index.vue"),
  PluginPdf: () => import("@/views/plugin/pdf/index.vue"),
  PluginPinyin: () => import("@/views/plugin/pinyin/index.vue"),
  PluginPrint: () => import("@/views/plugin/print/index.vue"),
  PluginSwiper: () => import("@/views/plugin/swiper/index.vue"),
  PluginTablesVtable: () => import("@/views/plugin/tables/vtable/index.vue"),
  PluginTypeit: () => import("@/views/plugin/typeit/index.vue"),
  PluginVideo: () => import("@/views/plugin/video/index.vue"),
  UserCenter: () => import("@/views/user-center/index.vue"),
};
