/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: '_builtin403',
    path: '/_builtin/403',
    layout: 'base',
    component: '_builtin403',
  },
  {
    name: '_builtin404',
    path: '/_builtin/404',
    layout: 'base',
    component: '_builtin404',
  },
  {
    name: '_builtin500',
    path: '/_builtin/500',
    layout: 'base',
    component: '_builtin500',
  },
  {
    name: '_builtinIframePageUrl',
    path: '/_builtin/iframe-page/:url',
    layout: 'base',
    component: '_builtinIframePageUrl',
  },
  {
    name: '_builtinLogin',
    path: '/_builtin/login',
    layout: 'base',
    component: '_builtinLogin',
  },
  {
    name: 'About',
    path: '/about',
    layout: 'base',
    component: 'About',
  },
  {
    name: 'AgentConfig',
    path: '/agent/config',
    layout: 'base',
    component: 'AgentConfig',
  },
  {
    name: 'AlovaRequest',
    path: '/alova/request',
    layout: 'base',
    component: 'AlovaRequest',
  },
  {
    name: 'AlovaScenes',
    path: '/alova/scenes',
    layout: 'base',
    component: 'AlovaScenes',
  },
  {
    name: 'AlovaUser',
    path: '/alova/user',
    layout: 'base',
    component: 'AlovaUser',
  },
  {
    name: 'FunctionHideChildOne',
    path: '/function/hide-child/one',
    layout: 'base',
    component: 'FunctionHideChildOne',
  },
  {
    name: 'FunctionHideChildThree',
    path: '/function/hide-child/three',
    layout: 'base',
    component: 'FunctionHideChildThree',
  },
  {
    name: 'FunctionHideChildTwo',
    path: '/function/hide-child/two',
    layout: 'base',
    component: 'FunctionHideChildTwo',
  },
  {
    name: 'FunctionMultiTab',
    path: '/function/multi-tab',
    layout: 'base',
    component: 'FunctionMultiTab',
  },
  {
    name: 'FunctionRequest',
    path: '/function/request',
    layout: 'base',
    component: 'FunctionRequest',
  },
  {
    name: 'FunctionSuperPage',
    path: '/function/super-page',
    layout: 'base',
    component: 'FunctionSuperPage',
  },
  {
    name: 'FunctionTab',
    path: '/function/tab',
    layout: 'base',
    component: 'FunctionTab',
  },
  {
    name: 'FunctionToggleAuth',
    path: '/function/toggle-auth',
    layout: 'base',
    component: 'FunctionToggleAuth',
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
  },
  {
    name: 'ManageAgent',
    path: '/manage/agent',
    layout: 'base',
    component: 'ManageAgent',
  },
  {
    name: 'ManageApi',
    path: '/manage/api',
    layout: 'base',
    component: 'ManageApi',
  },
  {
    name: 'ManageLog',
    path: '/manage/log',
    layout: 'base',
    component: 'ManageLog',
  },
  {
    name: 'ManageMenu',
    path: '/manage/menu',
    layout: 'base',
    component: 'ManageMenu',
  },
  {
    name: 'ManageRole',
    path: '/manage/role',
    layout: 'base',
    component: 'ManageRole',
  },
  {
    name: 'ManageUser',
    path: '/manage/user',
    layout: 'base',
    component: 'ManageUser',
  },
  {
    name: 'ManageUserDetailId',
    path: '/manage/user-detail/:id',
    layout: 'base',
    component: 'ManageUserDetailId',
  },
  {
    name: 'Medic',
    path: '/medic',
    layout: 'base',
    component: 'Medic',
  },
  {
    name: 'MedicalDiseaseList',
    path: '/medical/disease-list',
    layout: 'base',
    component: 'MedicalDiseaseList',
  },
  {
    name: 'MedicalExecutionDetailId',
    path: '/medical/execution-detail/:id',
    layout: 'base',
    component: 'MedicalExecutionDetailId',
  },
  {
    name: 'MultiMenuFirstChild',
    path: '/multi-menu/first_child',
    layout: 'base',
    component: 'MultiMenuFirstChild',
  },
  {
    name: 'MultiMenuSecondChildHome',
    path: '/multi-menu/second_child_home',
    layout: 'base',
    component: 'MultiMenuSecondChildHome',
  },
  {
    name: 'PluginBarcode',
    path: '/plugin/barcode',
    layout: 'base',
    component: 'PluginBarcode',
  },
  {
    name: 'PluginChartsAntv',
    path: '/plugin/charts/antv',
    layout: 'base',
    component: 'PluginChartsAntv',
  },
  {
    name: 'PluginChartsEcharts',
    path: '/plugin/charts/echarts',
    layout: 'base',
    component: 'PluginChartsEcharts',
  },
  {
    name: 'PluginChartsVchart',
    path: '/plugin/charts/vchart',
    layout: 'base',
    component: 'PluginChartsVchart',
  },
  {
    name: 'PluginCopy',
    path: '/plugin/copy',
    layout: 'base',
    component: 'PluginCopy',
  },
  {
    name: 'PluginEditorMarkdown',
    path: '/plugin/editor/markdown',
    layout: 'base',
    component: 'PluginEditorMarkdown',
  },
  {
    name: 'PluginEditorQuill',
    path: '/plugin/editor/quill',
    layout: 'base',
    component: 'PluginEditorQuill',
  },
  {
    name: 'PluginExcel',
    path: '/plugin/excel',
    layout: 'base',
    component: 'PluginExcel',
  },
  {
    name: 'PluginGanttDhtmlx',
    path: '/plugin/gantt/dhtmlx',
    layout: 'base',
    component: 'PluginGanttDhtmlx',
  },
  {
    name: 'PluginGanttVtable',
    path: '/plugin/gantt/vtable',
    layout: 'base',
    component: 'PluginGanttVtable',
  },
  {
    name: 'PluginIcon',
    path: '/plugin/icon',
    layout: 'base',
    component: 'PluginIcon',
  },
  {
    name: 'PluginMap',
    path: '/plugin/map',
    layout: 'base',
    component: 'PluginMap',
  },
  {
    name: 'PluginPdf',
    path: '/plugin/pdf',
    layout: 'base',
    component: 'PluginPdf',
  },
  {
    name: 'PluginPinyin',
    path: '/plugin/pinyin',
    layout: 'base',
    component: 'PluginPinyin',
  },
  {
    name: 'PluginPrint',
    path: '/plugin/print',
    layout: 'base',
    component: 'PluginPrint',
  },
  {
    name: 'PluginSwiper',
    path: '/plugin/swiper',
    layout: 'base',
    component: 'PluginSwiper',
  },
  {
    name: 'PluginTablesVtable',
    path: '/plugin/tables/vtable',
    layout: 'base',
    component: 'PluginTablesVtable',
  },
  {
    name: 'PluginTypeit',
    path: '/plugin/typeit',
    layout: 'base',
    component: 'PluginTypeit',
  },
  {
    name: 'PluginVideo',
    path: '/plugin/video',
    layout: 'base',
    component: 'PluginVideo',
  },
  {
    name: 'UserCenter',
    path: '/user-center',
    layout: 'base',
    component: 'UserCenter',
  }
];
