/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteKey, RoutePathMap } from '@elegant-router/types';

const routePathMap: RoutePathMap = {
  "Root": "/",
  "NotFound": "/:pathMatch(.*)*",
  "_builtin403": "/_builtin/403",
  "_builtin404": "/_builtin/404",
  "_builtin500": "/_builtin/500",
  "_builtinIframePageUrl": "/_builtin/iframe-page/:url",
  "_builtinLogin": "/_builtin/login",
  "About": "/about",
  "AgentConfig": "/agent/config",
  "AlovaRequest": "/alova/request",
  "AlovaScenes": "/alova/scenes",
  "AlovaUser": "/alova/user",
  "FunctionHideChildOne": "/function/hide-child/one",
  "FunctionHideChildThree": "/function/hide-child/three",
  "FunctionHideChildTwo": "/function/hide-child/two",
  "FunctionMultiTab": "/function/multi-tab",
  "FunctionRequest": "/function/request",
  "FunctionSuperPage": "/function/super-page",
  "FunctionTab": "/function/tab",
  "FunctionToggleAuth": "/function/toggle-auth",
  "Home": "/home",
  "ManageAgent": "/manage/agent",
  "ManageApi": "/manage/api",
  "ManageLog": "/manage/log",
  "ManageMenu": "/manage/menu",
  "ManageRole": "/manage/role",
  "ManageUser": "/manage/user",
  "ManageUserDetailId": "/manage/user-detail/:id",
  "Medic": "/medic",
  "MedicalDiseaseList": "/medical/disease-list",
  "MedicalExecutionDetailId": "/medical/execution-detail/:id",
  "MultiMenuFirstChild": "/multi-menu/first_child",
  "MultiMenuSecondChildHome": "/multi-menu/second_child_home",
  "PluginBarcode": "/plugin/barcode",
  "PluginChartsAntv": "/plugin/charts/antv",
  "PluginChartsEcharts": "/plugin/charts/echarts",
  "PluginChartsVchart": "/plugin/charts/vchart",
  "PluginCopy": "/plugin/copy",
  "PluginEditorMarkdown": "/plugin/editor/markdown",
  "PluginEditorQuill": "/plugin/editor/quill",
  "PluginExcel": "/plugin/excel",
  "PluginGanttDhtmlx": "/plugin/gantt/dhtmlx",
  "PluginGanttVtable": "/plugin/gantt/vtable",
  "PluginIcon": "/plugin/icon",
  "PluginMap": "/plugin/map",
  "PluginPdf": "/plugin/pdf",
  "PluginPinyin": "/plugin/pinyin",
  "PluginPrint": "/plugin/print",
  "PluginSwiper": "/plugin/swiper",
  "PluginTablesVtable": "/plugin/tables/vtable",
  "PluginTypeit": "/plugin/typeit",
  "PluginVideo": "/plugin/video",
  "UserCenter": "/user-center",
};

export function getRoutePath(key: RouteKey) {
  return routePathMap[key];
}
